version: "3.3"
services:
  scriptables-redis:
    container_name: scriptables-redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - scriptables-redis:/data

  scriptables-mysqldb:
    container_name: scriptables-db
    image: mariadb:10.4
    restart: always
    env_file: .env
    volumes:
      - ./build/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./build/mysql/server.cnf:/etc/mysql/mariadb.conf.d/server.cnf
      - scriptables-mysqldb:/var/lib/mysql

  scriptables-server:
    container_name: scriptables-server
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SCRIPTABLES_SERVER_DSN_HOST}:${SCRIPTABLES_SERVER_DSN_PORT}:${SCRIPTABLES_SERVER_DSN_PORT}"
    depends_on:
      - scriptables-redis
      - scriptables-mysqldb

volumes:
  scriptables-mysqldb:
  scriptables-redis: