#!/bin/bash
# exit-on-failure=yes

unset HISTFILE

sudo mysql <<'SQL'
CREATE DATABASE IF NOT EXISTS `#SITE_SLUG#`;
CREATE USER IF NOT EXISTS '#SITE_SLUG#'@'localhost' IDENTIFIED BY '#MYSQL_PASSWORD#';
GRANT ALL PRIVILEGES ON `#SITE_SLUG#`.* TO '#SITE_SLUG#'@'localhost';
FLUSH PRIVILEGES;
SQL
